---
  - name : Update yum packages
    yum: name=* state=latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name : install EPEL
    yum: name=epel-release state=latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name : install fail2ban
    yum: name=fail2ban state=latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: add universe repository
    apt_repository: repo='deb http://archive.ubuntu.com/ubuntu trusty universe' state=present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name : Update apt packages
    apt: upgrade=dist update_cache=yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name : install fail2ban
    apt: name=fail2ban state=latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name : add deployment user
    action: user name=deploy password={{deploy_password}}

  - name: Change root password
    action: user name=root password={{root_password}}

  - name : add SSH keys to deploy user
    authorized_key: user=deploy key=https://github.com/wadeschulz.keys

  - name : fix for selinux on key permissions
    cmd: sudo restorecon -R -v /home/deploy/.ssh
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Remove sudo group rights
    action: lineinfile dest=/etc/sudoers regexp="^%sudo" state=absent

  - name: Add deploy user to sudoers
    action: lineinfile dest=/etc/sudoers regexp="deploy ALL" line="deploy ALL=(ALL) ALL" state=present

  - name: Disallow root SSH access
    action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present

  - name: Disallow password authentication
    action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present

  - name: Restart sshd
    action: service name=sshd state=restarted
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: Restart ssh for ubuntu
    action: service name=ssh state=restarted
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
