# Pull base image.
FROM java:8-jre

# Apt-get Update
RUN apt-get -qqy update

WORKDIR /opt

RUN wget https://download.elastic.co/kibana/kibana/kibana-4.3.1-linux-x64.tar.gz

RUN tar -xzvf kibana-4.3.1-linux-x64.tar.gz && rm -f kibana-4.3.1-linux-x64.tar.gz && mv kibana-4.3.1-linux-x64 kibana

ENV ES_HOME=/opt/kibana

WORKDIR $ES_HOME

RUN bin/kibana plugin --install elasticsearch/marvel/latest

EXPOSE 5601

ENTRYPOINT $ES_HOME/bin/kibana