hdp:
      #
      # Cluster def and config
      #
      default_password : hadoop
      # Cluster version, should be of the form : 1.3.3 or 2.0.6
      HDP_VERSION : 2.3

      # Cluster Name
      CLUSTERNAME : labhdp

      # Mount points 
      dfs_datanode_data_dir : /hadoop/hdfs/data
      dfs_namenode_checkpoint_dir : /hadoop/hdfs/namesecondary
      dfs_namenode_name_dir : /hadoop/hdfs/namenode
      yarn_nodemanager_local_dirs : /hadoop/yarn/local
      yarn_nodemanager_log_dirs : /var/log/hadoop/yarn
      yarn_log_dir_prefix : /var/log/hadoop/yarn
      hbase_log_dir : /var/log/hadoo/hbase
      hbase_tmp_dir : /hadoop/hbase
      hcat_log_dir : /var/log/hadoop/hcat
      hdfs_log_dir_prefix : /var/log/hadoop/hdfs
      hive_log_dir : /var/log/hadoop/hive
      mapred_log_dir_prefix : /var/log/hadoop/mapred
      oozie_data_dir : /hadoop/oozie
      oozie_log_dir : /var/log/hadoop/oozie
      zk_data_dir : /hadoop/zookeeper
      zk_log_dir : /var/log/hadoop/zookeeper
