---
- hosts: all
  user: root
  become: yes
  become_method: sudo

  roles:
   - docker
   - elastic

  vars:
   - docker_users: root
   - cluster_name: datasci-elasticprod
   # max heap size per container should be 30.5g or 1/2 avail mem, whichever is smaller
   - es_heap_size: 3g