---
- hosts: all
  user: deploy
  become: yes
  become_method: sudo

  roles:
   - docker
   - elastic

  vars:
   - docker_users:
     - deploy
   - cluster_name: darkstar
   # max heap size per container should be 30.5g or 1/2 avail mem, whichever is smaller
   - es_heap_size: 3g