---
- hosts: all
  user: deploy
  become: yes
  become_method: sudo

  roles:
   - docker
   - elastic

  vars:
   - docker_users:
     - deploy
   - cluster_name: darkstar
   - master1: 10.71.30.33
   - master2: 10.71.30.35
   - master3: 10.71.30.49