- hosts: all
  vars_files:
   - vars/hdp.yml
   - vars/network_info.yml
   - vars/users.yml
   - vars/repository_info.yml
  user : root
  roles:
   - init
   - selinux
   - ntp
   - prereq
   - repository

- hosts: ambari_server
  user : root
  vars_files:
   - vars/repository_info.yml
   - vars/hdp.yml
  roles:
   - ambari-server
