--- 
   - name: add hdp groups
     group: name={{ item.name }} gid={{ item.gid }} state=present
     with_items: "{{hdp_groups}}"
   
   - name: add hdp users
     user: name={{ item.name }} uid={{ item.uid }} group={{ item.groups }} state=present
     with_items: "{{hdp_users}}"